# Generated by Django 5.2.7 on 2025-11-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('RECEIVE', 'Inbound Receive'), ('PICK', 'Outbound Pick'), ('ADJUST', 'Inventory Adjustment')], max_length=20)),
                ('sku_snapshot', models.CharField(max_length=50)),
                ('location_snapshot', models.CharField(max_length=20)),
                ('quantity_change', models.IntegerField()),
            ],
        ),
    ]
