# Generated by Django 5.2.7 on 2025-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_inventory_reserved_quantity_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='qty_picked',
            field=models.IntegerField(default=0),
        ),
    ]
