# Generated by Django 5.2.7 on 2025-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_orderline_qty_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('PICKED', 'Picked'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('RECEIVE', 'Inbound Receive'), ('PICK', 'Outbound Pick'), ('ADJUST', 'Inventory Adjustment'), ('SHIP', 'Order Shipped')], max_length=20),
        ),
    ]
