# Generated by Django 5.2.7 on 2025-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_order_status_alter_transactionlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('RECEIVE', 'Inbound Receive'), ('PICK', 'Outbound Pick'), ('ADJUST', 'Inventory Adjustment'), ('PACK', 'Order Packed'), ('SHIP', 'Order Shipped')], max_length=20),
        ),
    ]
