# Generated by Django 5.2.7 on 2025-11-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order_customer_address_order_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received (Restocked)'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='RMALine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to_return', models.IntegerField()),
                ('qty_received', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.rma')),
            ],
        ),
    ]
