# Generated by Django 5.2.7 on 2025-11-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_cyclecountsession_cyclecounttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('RECEIVE', 'Inbound Receive'), ('PICK', 'Outbound Pick'), ('ADJUST', 'Inventory Adjustment'), ('PACK', 'Order Packed'), ('SHIP', 'Order Shipped'), ('MOVE', 'Internal Move')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='location_snapshot',
            field=models.CharField(max_length=50),
        ),
    ]
