# Generated by Django 5.2.7 on 2025-11-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=20, unique=True)),
                ('location_type', models.CharField(choices=[('PICK', 'Pick Face'), ('RESERVE', 'Reserve Storage'), ('DOCK', 'Dock Door'), ('STAGING', 'Staging Area')], default='RESERVE', max_length=20)),
                ('zone', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
