# Generated by Django 5.2.7 on 2025-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
