# Generated by Django 5.2.7 on 2025-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_location_x_location_y'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('item', 'location_code', 'lot_number', 'status')},
        ),
    ]
