# Generated by Django 5.2.7 on 2025-11-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventory_unique_together_inventory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('RETURNED', 'Returned')], default='IN_STOCK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_serials', to='inventory.orderline')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location')),
            ],
        ),
    ]
