# Generated by Django 5.2.7 on 2025-11-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_pickbatch_orderline_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='batch',
        ),
        migrations.AddField(
            model_name='item',
            name='abc_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.pickbatch'),
        ),
    ]
