# Generated by Django 5.2.7 on 2025-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_orderline_batch_item_abc_class_order_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_items', models.IntegerField()),
                ('total_locations_used', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
