# Generated by Django 5.2.7 on 2025-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_dailyinventorysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
